apiVersion: v1
kind: Service
metadata:
  name: example-order
  namespace: aws-ttt-3
spec:
  selector:
    app: example-order
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080